allowBuilds:
  '@firebase/util': true
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  postcss: "^8.5.15"
